#!/usr/bin/env python3
"""Build a vocabulary file for a document that has no hand-written one.

    python3 scripts/make_preamble.py --doc sdei

The `tail` and `selected` arms differ from `nopre` by showing the model a
vocabulary. That vocabulary is PROMPT CONTEXT ONLY -- it is never compiled, so
it does not have to be valid Verus, and building one is therefore cheap. Rule
checking never invokes Verus either. (A repair arm would need a compilable
preamble; those arms are not run here, and on alp14 they produced the same
dangling-output set as their non-repair counterparts anyway.)

Contents are taken from the document itself, not invented:
  - return codes, from extractor 2, which reads the document's own code table
  - function IDs, scraped from each command's parameter table
  - shared primitive aliases, which every one of these SMC-convention specs uses

Modelled on training-dataset/specs/psci_13/preamble.rs, which is the
hand-written example: primitives, then codes, then FIDs, then state.
"""
import argparse, json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SECTIONS = ROOT / "training-dataset" / "sections"
RETURNS = ROOT / "results" / "returns"

PRIMS = """use vstd::prelude::*;

verus! {

// ---------------------------------------------------------------------------
// Primitive aliases (shared with the RMM layer for interoperability)
// ---------------------------------------------------------------------------

type UInt32  = u32;
type UInt64  = u64;
type Int32   = i32;
type Int64   = i64;
type Bits64  = u64;
type Address = u64;
"""

FID = re.compile(r'(?:Function ID|FID)\s*(0x[0-9A-Fa-f_]{6,})')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--doc", required=True)
    ap.add_argument("--prefix", default=None,
                    help="constant prefix; defaults to the document name upper-cased")
    a = ap.parse_args()

    sec = SECTIONS / a.doc
    if not sec.is_dir():
        sys.exit(f"no sections for {a.doc} -- run extractor 1 first")
    pre = (a.prefix or a.doc.split("_")[0]).upper()

    codes = []
    rf = RETURNS / f"returns-{a.doc}.json"
    if rf.exists():
        codes = json.load(open(rf))["vocab"]
    else:
        print(f"[warn] {rf} missing -- no return codes in the vocabulary", file=sys.stderr)

    fids = {}
    for p in sorted(sec.glob("*_command.txt")):
        cmd = p.name[:-len("_command.txt")]
        m = FID.search(p.read_text(errors="replace"))
        if m:
            fids[cmd] = m.group(1).replace("_", "")

    out = [PRIMS]
    if codes:
        out.append(f"\n// ---------------------------------------------------------------------------\n"
                   f"// {pre} return codes (from the document's own Return codes table)\n"
                   f"// ---------------------------------------------------------------------------\n")
        # Values are deliberately absent: the document gives them, but a wrong
        # guess here would be worse than none, and this file is read as
        # vocabulary rather than compiled.
        for c in codes:
            out.append(f"pub spec const {pre}_{c}: int;")
    if fids:
        out.append(f"\n\n// ---------------------------------------------------------------------------\n"
                   f"// Function IDs, scraped from each command's parameter table\n"
                   f"// ---------------------------------------------------------------------------\n")
        for c, v in sorted(fids.items()):
            out.append(f"pub spec const {c}_FID: int = {v};")
    out.append("""

// ---------------------------------------------------------------------------
// Machine state. Opaque on purpose: these documents describe state in prose,
// so inventing a field layout would put words in the specification's mouth.
// ---------------------------------------------------------------------------

pub struct S;

} // verus!
""")
    d = ROOT / "training-dataset" / "specs" / a.doc
    d.mkdir(parents=True, exist_ok=True)
    dest = d / "preamble.rs"
    # Refuse to clobber a hand-written vocabulary. psci_13's is 126 lines of
    # curated constants -- function IDs, affinity states, a real state struct --
    # and this generator produced a 10-constant file over the top of it before
    # this guard existed. Generated files carry the marker; hand-written ones
    # do not.
    MARK = "// generated by scripts/make_preamble.py"
    if dest.exists() and MARK not in dest.read_text():
        sys.exit(f"refusing to overwrite hand-written {dest}\n"
                 f"  (delete it first if that is really what you want)")
    dest.write_text(MARK + "\n" + "\n".join(out))
    print(f"{a.doc}: {len(codes)} return codes, {len(fids)} function IDs "
          f"-> {d/'preamble.rs'}")


if __name__ == "__main__":
    main()
